### ISSUE TITLE
When I use your codes in qt-4.5.0, it occured some problem

### ISSUE THREAD

**Issue by GitFuture** [gaudecker/qt-json#43]
when I want to compile my qt program with qt-4.5.0
it told me that ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<QVariant>’
as the picture showed 
![image](https://cloud.githubusercontent.com/assets/7582298/20205733/0d6f84b2-a816-11e6-8548-dda14d64b091.png)

**Comment by GitFuture** [comment]
But when I use it with qt-4.8.7, it works well

**Comment by martinrotter** [comment]
Qt < 4.7 contains much forward incompatible code. I would expect Qt-Json to work with Qt 4.7.3 or perhaps Qt 4.8.0 and higher.

**Comment by GitFuture** [comment]
Oh I found the solution at [http://stackoverflow.com/questions/3887064/qvariant-to-qobject](http://stackoverflow.com/questions/3887064/qvariant-to-qobject)

I change the function realization like following

```
Object& operator=(const QVariant& rhs) { 
    QObject * obj = qvariant_cast<QObject *>(rhs);
//  setValue(rhs);
    setValue(obj);
    return *this;
}
```

And it can worked for my application.

![image](https://cloud.githubusercontent.com/assets/7582298/20206181/a533bd42-a819-11e6-902a-a64769e13f02.png)

**Comment by GitFuture** [comment]
Yes, I can't agree more, but I have to use qt-4.5.0 for arm compiling, so I don't have other choice.

**Comment by martinrotter** [comment]
Maybe you could create pull request. This changes seems pretty much safe/compatible with rest of Qt versions.
